name: CI
on: [push]
jobs:
  test:
    name: Run tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Install build dependencies
      shell: pwsh
      run: ./install-build-dependencies.ps1
    - name: Test
      shell: pwsh
      run: ./build.ps1 Test